"""
Django settings for the cycle_invoice project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent.parent  # three levels up to reach the project root
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")  # keep the secret key used in production secret!
DEBUG = os.environ.get("DJANGO_DEBUG", "0").lower() in ("1", "true", "yes")  # don't run with debug turned on

# Set Allowed Hosts
raw_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(",") if h.strip()]
for host in ("127.0.0.1", "localhost"):
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Application definition
HIGH_PRIORITY_THIRD_PARTY_APPS = [
    "constance",  # for configuration management
]

LOCAL_APPS = [
    "cycle_invoice.accounting.apps.AccountingConfig",  # for accounting management
    "cycle_invoice.api.apps.ApiConfig",  # for API endpoints
    "cycle_invoice.common.apps.CommonConfig",  # for common utilities
    "cycle_invoice.party.apps.ContactConfig",  # for contact management,
    "cycle_invoice.product.apps.ProductConfig",  # for product management
    "cycle_invoice.sale.apps.SaleConfig",  # for sale management
    "cycle_invoice.subscription.apps.SubscriptionConfig",  # for subscription management
    "cycle_invoice.work.apps.WorkConfig",  # for work management
]

THIRD_PARTY_APPS = [
    "simple_history",  # for history tracking
    "storages",  # for S3 storage
    "polymorphic",  # for polymorphic models
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    *HIGH_PRIORITY_THIRD_PARTY_APPS,
    *LOCAL_APPS,
    *THIRD_PARTY_APPS,
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",  # for history tracking
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DJANGO_DB_NAME", "cycleinvoice"),
        "USER": os.getenv("DJANGO_DB_USER", "cycleinvoice"),
        "PASSWORD": os.getenv("DJANGO_DB_PASSWORD"),
        "HOST": os.getenv("DJANGO_DB_HOST", "localhost"),
        "PORT": os.getenv("DJANGO_DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    "127.0.0.1",
]

# REST Framework Settings
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}

# Custom User Model
AUTH_USER_MODEL = "common.User"

# System user used for automated tasks (created on demand)
# Configure via env var DJANGO_SYSTEM_USER_EMAIL if desired
SYSTEM_USER_EMAIL = os.environ.get("DJANGO_SYSTEM_USER_EMAIL", "system@cycleinvoice.local")

# Checks for runtime
if not SECRET_KEY and not DEBUG:
    error_message = "DJANGO_SECRET_KEY is required when DEBUG is False"
    raise RuntimeError(error_message)

from config.settings.celery import *  # noqa: E402, F403
from config.settings.constance import *  # noqa: E402, F403
from config.settings.jwt import *  # noqa: E402, F403
from config.settings.logging import *  # noqa: E402, F403
from config.settings.storage import *  # noqa: E402, F403
