# Generated by Django 5.2.2 on 2025-06-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
    ]
