# Generated by Django 5.2.2 on 2025-06-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='disabled',
        ),
    ]
