# Generated by Django 5.1.7 on 2025-04-11 06:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('contact', '0002_address_additional_alter_address_zip_code_and_more'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSaleWork',
            fields=[
                ('saleitem_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sale.saleitem')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('billed', 'Billed')], default='draft', max_length=20, verbose_name='status')),
                ('work_date', models.DateField(verbose_name='work date')),
                ('work_time', models.IntegerField(help_text='in minutes', verbose_name='work time')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='comment')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account_buy', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('account_sell', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.organisation', verbose_name='customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact', verbose_name='worker')),
            ],
            options={
                'verbose_name': 'historical Sale Work',
                'verbose_name_plural': 'historical Sale Works',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SaleWork',
            fields=[
                ('saleitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.saleitem')),
                ('work_date', models.DateField(verbose_name='work date')),
                ('work_time', models.IntegerField(help_text='in minutes', verbose_name='work time')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='comment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_work_customer', to='contact.organisation', verbose_name='customer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_work_worker', to='contact.contact', verbose_name='worker')),
            ],
            options={
                'verbose_name': 'Sale Work',
                'verbose_name_plural': 'Sale Works',
            },
            bases=('sale.saleitem',),
        ),
    ]
