# Generated by Django 5.1.7 on 2025-04-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('sale_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalework',
            name='account_buy',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='historicalsalework',
            name='account_sell',
            field=models.ForeignKey(blank=True, db_constraint=False, default=2000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='historicalsalework',
            name='comment',
            field=models.TextField(blank=True, max_length=255, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='salework',
            name='comment',
            field=models.TextField(blank=True, max_length=255, verbose_name='comment'),
        ),
    ]
