# Generated by Django 5.1.7 on 2025-04-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_work', '0003_alter_historicalsalework_account_buy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salework',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salework',
            name='saleitem_ptr',
        ),
        migrations.RemoveField(
            model_name='salework',
            name='worker',
        ),
        migrations.DeleteModel(
            name='HistoricalSaleWork',
        ),
        migrations.DeleteModel(
            name='SaleWork',
        ),
    ]
