# Generated by Django 5.2.9 on 2025-12-28 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('party', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='documentitem',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='documentitem',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sale_document_item_account', to='accounting.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicaldocumentitem',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='historicaldocumentitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_document_item_party', to='party.party'),
        ),
    ]
