# Generated by Django 5.2.2 on 2025-06-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('sale', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='comment_description',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='comment_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='comment title'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='comment_description',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='comment_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='comment title'),
        ),
        migrations.AddConstraint(
            model_name='documentitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', ['product', 'subscription', 'work', 'expense_vehicle'])), name='sale_documentitem_validate_item_type'),
        ),
        migrations.AddConstraint(
            model_name='documentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'product'), ('product__isnull', False), ('subscription__isnull', True), ('work_type__isnull', True), ('vehicle__isnull', True), ('comment_title', ''), ('comment_description', '')), models.Q(('item_type', 'product'), _negated=True), _connector='OR'), name='sale_documentitem_fields_match_product'),
        ),
        migrations.AddConstraint(
            model_name='documentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'subscription'), ('subscription__isnull', False), ('product__isnull', False), ('comment_title__isnull', False), models.Q(('comment_title', ''), _negated=True), ('work_type__isnull', True), ('vehicle__isnull', True), ('comment_description', '')), models.Q(('item_type', 'subscription'), _negated=True), _connector='OR'), name='sale_documentitem_fields_match_subscription'),
        ),
        migrations.AddConstraint(
            model_name='documentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'work'), ('work_type__isnull', False), ('comment_title__isnull', False), models.Q(('comment_title', ''), _negated=True), ('product__isnull', True), ('subscription__isnull', True), ('vehicle__isnull', True)), models.Q(('item_type', 'work'), _negated=True), _connector='OR'), name='sale_documentitem_fields_match_work'),
        ),
        migrations.AddConstraint(
            model_name='documentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'expense_vehicle'), ('vehicle__isnull', False), ('comment_title__isnull', False), models.Q(('comment_title', ''), _negated=True), ('comment_description__isnull', False), models.Q(('comment_description', ''), _negated=True), ('product__isnull', True), ('subscription__isnull', True), ('work_type__isnull', True)), models.Q(('item_type', 'expense_vehicle'), _negated=True), _connector='OR'), name='sale_documentitem_fields_match_expense_vehicle'),
        ),
    ]
