# Generated by Django 5.2.9 on 2025-12-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='documentitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
            ],
        ),
    ]
