# Generated by Django 5.2.9 on 2025-12-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_documentitem_managers_documentitem_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='documentitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='discount value'),
        ),
        migrations.AddField(
            model_name='historicaldocumentitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='discount value'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('absolute', 'Absolute')], default='percent', max_length=10, verbose_name='discount type'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('absolute', 'Absolute')], default='percent', max_length=10, verbose_name='discount type'),
        ),
    ]
