# Generated by Django 5.2.9 on 2025-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_documentitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='discount value'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='discount value'),
        ),
    ]
