# Generated by Django 6.0 on 2026-01-04

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models

SYSTEM_EMAIL = "system@cycleinvoice.local"


def create_initial_system_user(apps, schema_editor):
    User = apps.get_model("common", "User")

    email = "system@cycleinvoice.local"

    if User.objects.filter(email=email).exists():
        return

    system_uuid = uuid.uuid4()

    User.objects.create(
        uuid=system_uuid,
        email=email,
        first_name="System",
        last_name="User",
        is_active=True,
        is_staff=False,
        is_superuser=False,
        password=make_password(None),  # unusable password
        created_by_id=system_uuid,
        updated_by_id=system_uuid,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),

                (
                    "uuid",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        db_index=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),

                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("soft_deleted", models.BooleanField(default=False, db_index=True, verbose_name="soft deleted")),

                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),

                (
                    "created_by",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        editable=False,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        editable=False,
                    ),
                ),

                (
                    "groups",
                    models.ManyToManyField(
                        to="auth.group",
                        blank=True,
                        related_name="user_set",
                        related_query_name="user",
                        verbose_name="groups",
                        help_text="The groups this user belongs to.",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        to="auth.permission",
                        blank=True,
                        related_name="user_set",
                        related_query_name="user",
                        verbose_name="user permissions",
                        help_text="Specific permissions for this user.",
                    ),
                ),
            ],
            options={"abstract": False},
        ),

        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, db_index=True, verbose_name="UUID")),
                ("created_at", models.DateTimeField(blank=True, editable=False, verbose_name="created at")),
                ("updated_at", models.DateTimeField(blank=True, editable=False, verbose_name="updated at")),
                ("soft_deleted", models.BooleanField(default=False, db_index=True, verbose_name="soft deleted")),
                ("email", models.EmailField(max_length=254, db_index=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),

                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        max_length=1,
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        editable=False,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        editable=False,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),

        migrations.RunPython(create_initial_system_user, migrations.RunPython.noop),
    ]
