# Generated by Django 5.2.2 on 2025-06-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestbasemodel',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='testbasemodel',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
