# Generated by Django 5.2.2 on 2025-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_historicaltestbasemodel_name_testbasemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestbasemodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='testbasemodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
