# Generated by Django 5.2.9 on 2025-12-25 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_created_updated_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='soft_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='soft deleted'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='soft_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='soft deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
