# Generated by Django 5.1.7 on 2025-04-07 20:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='additional',
            field=models.CharField(blank=True, max_length=255, verbose_name='additional'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=12, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='uid'),
        ),
        migrations.CreateModel(
            name='HistoricalAddress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('additional', models.CharField(blank=True, max_length=255, verbose_name='additional')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('zip_code', models.CharField(max_length=12, verbose_name='zip code')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical address',
                'verbose_name_plural': 'historical addresses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
