# Generated by Django 5.2 on 2025-05-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_customer_remove_contact_id_remove_organisation_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
