# Generated by Django 5.2.1 on 2025-06-07 15:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0004_remove_contact_address_remove_organisation_address_and_more'),
        ('sale', '0012_documentitem_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_internal', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('name_external', models.CharField(max_length=50, verbose_name='type')),
                ('km_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km buy')),
                ('km_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km sell')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_internal', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('name_external', models.CharField(max_length=50, verbose_name='type')),
                ('km_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km buy')),
                ('km_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km sell')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vehicle',
                'verbose_name_plural': 'historical Vehicles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentItemKilometers',
            fields=[
                ('documentitem_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sale.documentitem')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='quantity')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='discount percent')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.customer')),
                ('end_address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.address', verbose_name='end address')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.documentinvoice')),
                ('start_address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.address', verbose_name='start address')),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicle.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'historical Document Kilometer',
                'verbose_name_plural': 'historical Document Kilometers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentItemKilometers',
            fields=[
                ('documentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.documentitem')),
                ('end_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_item_kilometers_end_address', to='contact.address', verbose_name='end address')),
                ('start_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_item_kilometers_start_address', to='contact.address', verbose_name='start address')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_item_kilometers', to='vehicle.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Document Kilometer',
                'verbose_name_plural': 'Document Kilometers',
            },
            bases=('sale.documentitem',),
        ),
    ]
