# Generated by Django 6.0 on 2026-01-04 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +412345678', regex='^\\+?\\d{1,4} ?\\d{1,3} ?\\d{1,4} ?\\d{1,4} ?\\d{1,9}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +412345678', regex='^\\+?\\d{1,4} ?\\d{1,3} ?\\d{1,4} ?\\d{1,4} ?\\d{1,9}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalparty',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +412345678', regex='^\\+?\\d{1,4} ?\\d{1,3} ?\\d{1,4} ?\\d{1,4} ?\\d{1,9}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +412345678', regex='^\\+?\\d{1,4} ?\\d{1,3} ?\\d{1,4} ?\\d{1,4} ?\\d{1,9}$')], verbose_name='phone'),
        ),
    ]
