# Generated by Django 5.2.9 on 2025-12-21 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='organizationcontact',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='party',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='polymorphic_ctype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='polymorphic_ctype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='polymorphic_ctype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='party',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
