# Generated by Django 5.2.2 on 2025-06-17 17:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_internal', models.CharField(max_length=255, unique=True, verbose_name='internal name')),
                ('name_external', models.CharField(max_length=50, verbose_name='external name')),
                ('km_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km buy')),
                ('km_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km sell')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_internal', models.CharField(db_index=True, max_length=255, verbose_name='internal name')),
                ('name_external', models.CharField(max_length=50, verbose_name='external name')),
                ('km_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km buy')),
                ('km_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='km sell')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vehicle',
                'verbose_name_plural': 'historical Vehicles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
