# Generated by Django 5.1.7 on 2025-04-25 07:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_address_additional_alter_address_zip_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True, verbose_name='domain name')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_customer', to='contact.organisation', verbose_name='customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDomain',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255, verbose_name='domain name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.organisation', verbose_name='customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical domain',
                'verbose_name_plural': 'historical domains',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWebsiteCheck',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('check_date', models.DateTimeField(blank=True, editable=False, verbose_name='check date')),
                ('google_fonts', models.BooleanField(default=False, verbose_name='google fonts')),
                ('mainwp_plugin', models.BooleanField(default=False, verbose_name='mainwp plugin')),
                ('backup_plugin', models.BooleanField(default=False, verbose_name='backup plugin')),
                ('up_to_date', models.BooleanField(default=False, verbose_name='up to date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('domain', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='domain.domain', verbose_name='domain')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical website check',
                'verbose_name_plural': 'historical website checks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WebsiteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, verbose_name='check date')),
                ('google_fonts', models.BooleanField(default=False, verbose_name='google fonts')),
                ('mainwp_plugin', models.BooleanField(default=False, verbose_name='mainwp plugin')),
                ('backup_plugin', models.BooleanField(default=False, verbose_name='backup plugin')),
                ('up_to_date', models.BooleanField(default=False, verbose_name='up to date')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_check_domain', to='domain.domain', verbose_name='domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
