# Generated by Django 5.1.7 on 2025-04-25 08:04

import accounting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('contact', '0002_address_additional_alter_address_zip_code_and_more'),
        ('domain', '0002_historicalhostingproduct_and_more'),
        ('sale', '0004_subscriptionitem_remove_saleitem_account_buy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingProduct',
            fields=[
                ('saleproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.saleproduct')),
                ('storage_capacity', models.PositiveIntegerField(default=0, verbose_name='storage capacity (GB)')),
            ],
            options={
                'verbose_name': 'hosting product',
                'verbose_name_plural': 'hosting products',
            },
            bases=('sale.saleproduct',),
        ),
        migrations.RemoveField(
            model_name='websitecheck',
            name='domain',
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
        migrations.AddField(
            model_name='historicalhostingproduct',
            name='account_buy',
            field=models.ForeignKey(blank=True, db_constraint=False, default=accounting.models.get_default_account_buy, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='historicalhostingproduct',
            name='account_sell',
            field=models.ForeignKey(blank=True, db_constraint=False, default=accounting.models.get_default_account_sell, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='historicalhostingproduct',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhostingsubscription',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.organisation', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='historicalhostingsubscription',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhostingsubscription',
            name='hosting_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.saleproduct', verbose_name='hosting product'),
        ),
        migrations.CreateModel(
            name='HostingSubscription',
            fields=[
                ('subscriptionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.subscriptionitem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_customer', to='contact.organisation', verbose_name='customer')),
                ('hosting_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_product', to='sale.saleproduct', verbose_name='hosting product')),
            ],
            options={
                'verbose_name': 'hosting',
                'verbose_name_plural': 'hostings',
            },
            bases=('sale.subscriptionitem',),
        ),
        migrations.DeleteModel(
            name='HistoricalWebsiteCheck',
        ),
        migrations.DeleteModel(
            name='WebsiteCheck',
        ),
    ]
