# Generated by Django 5.1.7 on 2025-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_hostingproduct_remove_websitecheck_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhostingproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhostingsubscription',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
