# Generated by Django 5.2.9 on 2025-12-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubscription',
            old_name='customer',
            new_name='party',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='customer',
            new_name='party',
        ),
    ]
