# Generated by Django 6.0 on 2026-01-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemail',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=255),
        ),
    ]
