# Generated by Django 5.1.7 on 2025-04-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_setting'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='subscription_only',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subscription_only',
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='account_buy',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='account_sell',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_buy',
            field=models.ForeignKey(default=4000, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sale_product_buy_account', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_sell',
            field=models.ForeignKey(default=3000, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sale_products_sell_account', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='price'),
        ),
    ]
