# Generated by Django 5.2.1 on 2025-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='canceled date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='canceled date'),
        ),
    ]
