# Generated by Django 5.1.7 on 2025-04-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsaleitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sale Item', 'verbose_name_plural': 'historical Sale Items'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AlterField(
            model_name='historicalsaleitem',
            name='account_buy',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='historicalsaleitem',
            name='account_sell',
            field=models.ForeignKey(blank=True, db_constraint=False, default=2000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='account_buy',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sale_items_buy_account', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='account_sell',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sale_items_sell_account', to='accounting.account'),
        ),
    ]
