# Generated by Django 5.2.2 on 2025-06-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_documentitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_item_work_type', to='sale.worktype'),
        ),
        migrations.AddField(
            model_name='historicaldocumentitem',
            name='work_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.worktype'),
        ),
    ]
