# Generated by Django 5.1.7 on 2025-04-17 06:38

import accounting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('sale', '0002_alter_historicalsaleitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleitem',
            name='account_buy',
            field=models.ForeignKey(blank=True, db_constraint=False, default=accounting.models.get_default_account_buy, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='historicalsaleitem',
            name='account_sell',
            field=models.ForeignKey(blank=True, db_constraint=False, default=accounting.models.get_default_account_sell, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='account_buy',
            field=models.ForeignKey(default=accounting.models.get_default_account_buy, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sale_items_buy_account', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='account_sell',
            field=models.ForeignKey(default=accounting.models.get_default_account_sell, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sale_items_sell_account', to='accounting.account'),
        ),
    ]
