# Generated by Django 5.1.7 on 2025-04-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_historicalproduct_subscription_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='price'),
        ),
    ]
