# Generated by Django 5.2.2 on 2025-06-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_historicalsubscription_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubscription',
            old_name='canceled_date',
            new_name='cancelled_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='canceled_date',
            new_name='cancelled_date',
        ),
    ]
