# Generated by Django 5.2.1 on 2025-05-20 20:48

import accounting.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_historicaltransaction_transaction_historicalpayment'),
        ('contact', '0003_alter_customer_options'),
        ('sale', '0002_historicalsubscription_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True, verbose_name='invoice number')),
                ('date', models.DateField(verbose_name='date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('header_text', models.TextField(blank=True, verbose_name='header text')),
                ('footer_text', models.TextField(blank=True, verbose_name='footer text')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_invoice', to='contact.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='quantity')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='discount percent')),
                ('item_group', models.CharField(max_length=255, verbose_name='item group')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_item', to='sale.documentinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=255, verbose_name='invoice number')),
                ('date', models.DateField(verbose_name='date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('header_text', models.TextField(blank=True, verbose_name='header text')),
                ('footer_text', models.TextField(blank=True, verbose_name='footer text')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Invoice',
                'verbose_name_plural': 'historical Invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='quantity')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='discount percent')),
                ('item_group', models.CharField(max_length=255, verbose_name='item group')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.documentinvoice')),
            ],
            options={
                'verbose_name': 'historical document item',
                'verbose_name_plural': 'historical document items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentProduct',
            fields=[
                ('documentitem_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sale.documentitem')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='quantity')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='discount percent')),
                ('item_group', models.CharField(max_length=255, verbose_name='item group')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.documentinvoice')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.product')),
            ],
            options={
                'verbose_name': 'historical Document Product',
                'verbose_name_plural': 'historical Document Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, default=accounting.models.get_default_sell_account, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Work Type',
                'verbose_name_plural': 'historical Work Types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('account', models.ForeignKey(default=accounting.models.get_default_sell_account, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='work_type_account', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWorkTypePrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.worktype')),
            ],
            options={
                'verbose_name': 'historical Work Type Price',
                'verbose_name_plural': 'historical Work Type Prices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkTypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type_price', to='sale.worktype')),
            ],
            options={
                'verbose_name': 'Work Type Price',
                'verbose_name_plural': 'Work Type Prices',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentWork',
            fields=[
                ('documentitem_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sale.documentitem')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='quantity')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='discount percent')),
                ('item_group', models.CharField(max_length=255, verbose_name='item group')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.documentinvoice')),
                ('work', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.worktypeprice')),
            ],
            options={
                'verbose_name': 'historical Document Work',
                'verbose_name_plural': 'historical Document Works',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentProduct',
            fields=[
                ('documentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.documentitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_product', to='sale.product')),
            ],
            options={
                'verbose_name': 'Document Product',
                'verbose_name_plural': 'Document Products',
            },
            bases=('sale.documentitem',),
        ),
        migrations.CreateModel(
            name='DocumentWork',
            fields=[
                ('documentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.documentitem')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_work', to='sale.worktypeprice')),
            ],
            options={
                'verbose_name': 'Document Work',
                'verbose_name_plural': 'Document Works',
            },
            bases=('sale.documentitem',),
        ),
    ]
