# Generated by Django 5.2.1 on 2025-06-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_rename_canceled_date_historicalsubscription_cancelled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionproduct',
            name='recurrence',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='recurrence',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10),
        ),
    ]
