# Generated by Django 5.2.1 on 2025-05-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_documentinvoice_documentitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_item', to='sale.documentinvoice'),
        ),
    ]
