# Generated by Django 5.2.2 on 2025-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_documentitem_work_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('subscription', 'Subscription'), ('work', 'Work'), ('expense_vehicle', 'Vehicle expense')], default='product', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='historicaldocumentitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('subscription', 'Subscription'), ('work', 'Work'), ('expense_vehicle', 'Vehicle expense')], default='product', max_length=20, verbose_name='Type'),
        ),
    ]
