# Generated by Django 5.1.7 on 2025-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_subscriptionitem_remove_saleitem_account_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
    ]
