# Generated by Django 5.2.2 on 2025-06-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_documentitem_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('subscription', 'Subscription'), ('work', 'Work'), ('expense_vehicle', 'Vehicle expense')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('subscription', 'Subscription'), ('work', 'Work'), ('expense_vehicle', 'Vehicle expense')], max_length=20, verbose_name='Type'),
        ),
    ]
