# Generated by Django 5.2.1 on 2025-05-21 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_documentitem_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentProduct',
            new_name='DocumentItemProduct',
        ),
        migrations.RenameModel(
            old_name='DocumentWork',
            new_name='DocumentItemWork',
        ),
        migrations.RenameModel(
            old_name='HistoricalDocumentProduct',
            new_name='HistoricalDocumentItemProduct',
        ),
        migrations.RenameModel(
            old_name='HistoricalDocumentWork',
            new_name='HistoricalDocumentItemWork',
        ),
    ]
