# Generated by Django 5.1.7 on 2025-04-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_historicalsaleproduct_price_saleproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsaleproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='saleproduct',
            name='price',
        ),
    ]
