# Generated by Django 5.2.1 on 2025-05-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_rename_documentproduct_documentitemproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
