# Generated by Django 5.2.1 on 2025-05-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_documentitemwork_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentitemwork',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='historicaldocumentitemwork',
            old_name='description',
            new_name='comment',
        ),
    ]
