# Generated by Django 5.2.1 on 2025-05-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_rename_description_documentitemwork_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentitem',
            name='item_group',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentitem',
            name='item_group',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentitemproduct',
            name='item_group',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentitemwork',
            name='item_group',
        ),
    ]
