# Generated by Django 5.2.1 on 2025-05-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_remove_documentitem_item_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworktype',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=14, verbose_name='price per hour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktype',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=14, verbose_name='price per hour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentitemwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_work', to='sale.worktype'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentitemwork',
            name='work',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.worktype'),
        ),
    ]
