# Generated by Django 5.2.1 on 2025-05-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_historicalworktype_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktypeprice',
            name='work_type',
        ),
        migrations.DeleteModel(
            name='HistoricalWorkTypePrice',
        ),
        migrations.DeleteModel(
            name='WorkTypePrice',
        ),
    ]
