# Generated by Django 5.2.1 on 2025-06-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contact_address_remove_organisation_address_and_more'),
        ('sale', '0011_remove_worktypeprice_work_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='document_item', to='contact.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocumentitem',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.customer'),
        ),
        migrations.AddField(
            model_name='historicaldocumentitemproduct',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.customer'),
        ),
        migrations.AddField(
            model_name='historicaldocumentitemwork',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.customer'),
        ),
    ]
