# Generated by Django 5.2.1 on 2025-06-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_documentitem_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_item', to='sale.documentinvoice'),
        ),
    ]
