# Generated by Django 5.2.1 on 2025-06-23 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('soft_deleted', True), models.Q(('default_buy', True), ('default_sell', True), _connector='OR'), _negated=True), name='accounting_account_prevent_soft_delete_if_default_buy_or_sell'),
        ),
    ]
