# Generated by Django 5.2 on 2025-05-03 10:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='account number')),
                ('default_buy', models.BooleanField(default=False,
                                                    help_text='Set this account as the default for buying transactions.',
                                                    verbose_name='default buy account')),
                ('default_sell', models.BooleanField(default=False,
                                                     help_text='Set this account as the default for selling transactions.',
                                                     verbose_name='default sell account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('number', models.CharField(db_index=True, max_length=20, verbose_name='account number')),
                ('default_buy', models.BooleanField(default=False,
                                                    help_text='Set this account as the default for buying transactions.',
                                                    verbose_name='default buy account')),
                ('default_sell', models.BooleanField(default=False,
                                                     help_text='Set this account as the default for selling transactions.',
                                                     verbose_name='default sell account')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Account',
                'verbose_name_plural': 'historical Accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
