# Generated by Django 5.1.7 on 2025-04-29 20:54

from django.db import migrations
from extra_settings.models import Setting

class Migration(migrations.Migration):

    def create_default_account_sell(apps, schema_editor):
        Account = apps.get_model("accounting", "Account")

        account_id = 3000
        account_name = "Default Account Sell"

        # Konto erstellen, falls es nicht existiert
        account, created = Account.objects.get_or_create(
            number=account_id,
            defaults={"name": account_name}
        )

        setting_obj = Setting(
            name="ACCOUNTING_DEFAULT_ACCOUNT_SELL",
            value_type=Setting.TYPE_INT,
            value=account_id,
            validators=["accounting.validators.validate_account_exists"],
            description="Default account for selling items",
        )
        setting_obj.save()

        account_id = 4000
        account_name = "Default Account Buy"

        # Konto erstellen, falls es nicht existiert
        account, created = Account.objects.get_or_create(
            number=account_id,
            defaults={"name": account_name}
        )

        setting_obj = Setting(
            name="ACCOUNTING_DEFAULT_ACCOUNT_BUY",
            value_type=Setting.TYPE_INT,
            value=account_id,
            validators=["accounting.validators.validate_account_exists"],
            description="Default account for buying items",
        )
        setting_obj.save()

    dependencies = [
        ('accounting', '0001_initial'),
        ('extra_settings', '0008_auto_20221024_0717'),
    ]

    operations = [
        migrations.RunPython(create_default_account_sell),
    ]
