# Generated by Django 5.1.7 on 2025-04-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_create_settings'),
        ('extra_settings', '0008_auto_20221024_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('extra_settings.setting',),
        ),
    ]
