name: Django Test Coverage

on:
  pull_request:

jobs:
  test-coverage:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: cycleinvoice
          POSTGRES_PASSWORD: cycleinvoice
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      CYCLEINVOICE_DJANGO_DB_HOST: localhost
      CYCLEINVOICE_DJANGO_SECRET_KEY: supersecretkey12345

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install coverage

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 5
          done

      - name: Run tests with coverage
        run: |
          coverage run --rcfile=.coveragerc manage.py test
          coverage report --fail-under=99
